---
title: Amati per Amare
timezone: Europe/Rome
collections:
  events:
    title: Eventi
    output: true
  books:
    title: Libri
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
    summary: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Roberto e Claudia
    summary: 
description: |-
  Corsi e ritiri per single, fidanzati, coppie di sposi e coppie in crisi. La psicologia al servizio della Paola di Dio, per percorsi esperienziali in cui crescere umanamente e spiritualmente nella fede e nell'amore di coppia.
  Obbiettivi degli incontri: fare un esperienza di Dio attraverso la preghiera, custodire la conoscenza della Parola e dei sacramenti. Consolidare le risorse dell'individuo e della coppia, affrontare le crisi, costruire un'intimità autentica, positiva e profonda.
url: http://amatiperamare.it
landing:
  image: "/uploads/logo%20amati%203%20(1).jpg"
  events_title: <i class="fa fa-calendar-o"></i> &nbsp; Eventi
  blog_title: <i class="fa fa-pencil"></i> &nbsp; Blog
  libri_title: <i class="fa fa-pencil"></i> &nbsp;Libri
footer:
  image: "/uploads/amati%20per%20amare1.png"
  text: Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)
navigation:
  landing:
  - title: Blog
    url: blog
    show: true
  - title: Eventi
    url: eventi
    show: true
  - title: Libri
    url: libri
    show: true
  other:
  - title: Chi siamo
    show: true
    url: chi-siamo
  - title: Scrivici
    url: mailto:info@amatiperamare.it
    show: false
  - title: Seguici su <i class="fa fa-facebook-square fa-lg"></i>
    url: https://www.facebook.com/AmatiperAmare/
    show: true
  - title: Seguici su <i class="fa fa-youtube-play"></i>
    url: https://www.youtube.com/channel/UCLhMktg9WhN92Ykn2yD61Wg/featured?view_as=subscriber
    show: true
    Key: 
permalink: "/:title"
markdown: kramdown
future: false
sass:
  sass_dir: _sass
  sourcemap: true
google_analytics: UA-80880832-1
facebook_app_id: 150639462009047
favicon_image: "/uploads/amati%20per%20amare1.png"
