---
title: Amati per amare
timezone: UTC
collections:
  events:
    title: Eventi
    output: true
    permalink: title
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
landing_page:
  blog: true
  blog_title: Blog
  events: true
  events_title: Eventi
footer_text: Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)
description: Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)
url: http://amatiperamare.it
favicon_img: "/images/favicon/logo.png"
landing_img: "/images/logo/logo-orizzontale-compatto.jpg"
permalink: "/:title"
markdown: kramdown
future: true
poole:
  word_separator: "-"
include:
- ".well-known"
sass:
  sass_dir: _sass
  sourcemap: true
about: "/chi-siamo"
