---
title: Amatiperamare.Github.Io
timezone: Europe/Rome
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
url: http://example.com
theme:
  title: Amati per amare
  avatar: "/uploads/eroico.jpg"
  gravatar: 
  description: La pagina ufficiale di Amati per amare
  header_text: "<p>Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)</p>"
  header_text_feature_image: 
  footer_text: Ispirati dalla fede Cristiana, crediamo che la persona, quando si sente
    amata e voluta bene fiorisce! E nell'amore... lì è Dio. Il nostro scopo è portare
    l'Amore di Gesù in particolare fra le coppie di sposi e fra coppie in crisi.
  rss: false
  email_address: info@amatiperamare.it
  behance: 
  bitbucket: 
  dribbble: 
  facebook: https://www.facebook.com/AmatiperAmare/
  flickr: 
  github: 
  google_plus: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  tumblr: 
  twitter: 
  wordpress: 
  youtube: 
  google_analytics: 
  disqus_shortname: 
  katex: true
  str_follow_on: Seguici su
  str_rss_follow: Sugui RSS feed
  str_email: Email
  str_next: Prossimo
  str_prev: Precedente
  str_continue_reading: Continua a leggere
  google_fonts: Source+Sans+Pro:400,700,700italic,400italic
  post_navigation: false
  favicon: "/uploads/eroico.jpg"
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
- jekyll-paginate
