---
title: Amati per amare
timezone: UTC
collections:
  events:
    title: Eventi
    output: true
    permalink: title
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
landing_page:
  blog: true
  blog_title: Blog
  events: true
  events_title: Eventi
footer_text: Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)
description: Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)
url: http://amatiperamare.it
favicon_image: "/images/logo/logo-web.png"
landing_image: "/images/logo/logo-orizzontale-compatto-web.jpg"
footer_image: "/images/logo/logo-web.png"
permalink: "/:title"
markdown: kramdown
future: true
poole:
  word_separator: "-"
include:
- ".well-known"
sass:
  sass_dir: _sass
  sourcemap: true
facebook: https://www.facebook.com/AmatiperAmare/
navigation:
  pages:
  - title: Blog
    url: blog
    show: true
  - title: Eventi
    url: eventi
    show: true
  external:
  - title: Scrivici
    url: mailto:info@amatiperamare.it
    show: true
  - title: Seguici su <i class="fa fa-facebook-square fa-lg"></i>
    url: https://www.facebook.com/AmatiperAmare/
    show: true
