---
title: Amati per amare
timezone: UTC
collections:
  events:
    title: Eventi
    output: true
    permalink: title
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
description: Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)
url: http://amatiperamare.it
permalink: "/:title"
markdown: kramdown
future: true
sass:
  sass_dir: _sass
  sourcemap: true
navigation:
  pages:
  - title: Blog
    url: blog
    show: true
  - title: Eventi
    url: eventi
    show: true
  external:
  - title: Scrivici
    url: mailto:info@amatiperamare.it
    show: true
  - title: Seguici su <i class="fa fa-facebook-square fa-lg"></i>
    url: https://www.facebook.com/AmatiperAmare/
    show: true
landing:
  events_title: <i class="fa fa-calendar-o"></i> &nbsp; Eventi
  blog_title: <i class="fa fa-pencil"></i> &nbsp; Blog
  image: "/images/logo/logo-orizzontale-compatto-web.jpg"
footer:
  image: "/images/logo/logo-web.png"
  text: "Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)"
