---
title: Amati per amare
timezone: Europe/Rome
collections:
  events:
    title: Eventi
    output: true
    permalink: title
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
    summary: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Roberto e Claudia
    summary: 
description: 'Corsi per fidanzati, coppie di sposi e coppie in crisi. La psicologia
  al servizio della Paola di Dio, per proporre percorsi esperienziali per crescere
  umanamente e spiritualmente nella fede e nell''amore di coppia. Obbiettivi degli
  incontri: consolidare le risorse nelle coppia, affrontare le crisi, costruire un''intimità
  autentica, positiva e profonda.'
url: http://amatiperamare.it
landing:
  image: "/images/logo/logo-orizzontale-compatto-web.jpg"
  events_title: <i class="fa fa-calendar-o"></i> &nbsp; Eventi
  blog_title: <i class="fa fa-pencil"></i> &nbsp; Blog
footer:
  image: "/images/logo/logo-web.png"
  text: Io sono con voi tutti i giorni, fino alla fine del mondo. (Mt 28,20)
navigation:
  landing:
  - title: Blog
    url: blog
    show: true
  - title: Eventi
    url: eventi
    show: true
  other:
  - title: Chi siamo
    show: true
    url: chi-siamo
  - title: Scrivici
    url: mailto:info@amatiperamare.it
    show: false
  - title: Seguici su <i class="fa fa-facebook-square fa-lg"></i>
    url: https://www.facebook.com/AmatiperAmare/
    show: true
permalink: "/:title"
markdown: kramdown
future: false
sass:
  sass_dir: _sass
  sourcemap: true
google_analytics: 
facebook_app_id: 150639462009047
